import type {
  KotlinAndroidOutputConfig,
  KotlinComposeOutputConfig,
  LocalizationCatalog,
  LocalizationEntry,
  Placeholder
} from "../types.js";
import { kotlinIdentifier, resourceIdentifier } from "../utils/names.js";

export function generateKotlinAndroid(
  catalog: LocalizationCatalog,
  config: KotlinAndroidOutputConfig
): string {
  const objectName = config.objectName ?? "L10n";
  const entries = [...catalog.entries].sort((a, b) => a.key.localeCompare(b.key));
  const lines = [
    "// Generated by l10n-codegen. Do not edit.",
    config.packageName ? `package ${config.packageName}` : "",
    "",
    "import android.content.Context",
    config.rImport ? `import ${config.rImport}` : "",
    "",
    `public object ${objectName} {`
  ].filter((line, index, array) => line !== "" || array[index - 1] !== "");

  for (const entry of entries) {
    lines.push(...androidEntry(entry, objectName), "");
  }

  lines.push("}");
  return `${lines.join("\n")}\n`;
}

export function generateKotlinCompose(
  catalog: LocalizationCatalog,
  config: KotlinComposeOutputConfig
): string {
  const objectName = config.objectName ?? "L10n";
  const entries = [...catalog.entries].sort((a, b) => a.key.localeCompare(b.key));
  const lines = [
    "// Generated by l10n-codegen. Do not edit.",
    config.packageName ? `package ${config.packageName}` : "",
    "",
    "import androidx.compose.runtime.Composable",
    "import org.jetbrains.compose.resources.pluralStringResource",
    "import org.jetbrains.compose.resources.stringArrayResource",
    "import org.jetbrains.compose.resources.stringResource",
    config.resImport ? `import ${config.resImport}` : "",
    "",
    `public object ${objectName} {`
  ].filter((line, index, array) => line !== "" || array[index - 1] !== "");

  for (const entry of entries) {
    lines.push(...composeEntry(entry, objectName), "");
  }

  lines.push("}");
  return `${lines.join("\n")}\n`;
}

function androidEntry(entry: LocalizationEntry, objectName: string): string[] {
  const name = kotlinIdentifier(entry.key, objectName);
  const resource = resourceIdentifier(entry.key);

  if (entry.kind === "array") {
    return [
      `    public fun ${name}(context: Context): Array<String> =`,
      `        context.resources.getStringArray(R.array.${resource})`
    ];
  }

  if (entry.kind === "plural") {
    const parameters = pluralParameters(entry.placeholders, true);
    const args = pluralFormatArgs(entry.placeholders);
    return [
      `    public fun ${name}(context: Context, ${parameters}): String =`,
      `        context.resources.getQuantityString(R.plurals.${resource}, quantity${args})`
    ];
  }

  if (entry.placeholders.length === 0) {
    return [`    public fun ${name}(context: Context): String = context.getString(R.string.${resource})`];
  }

  return [
    `    public fun ${name}(context: Context, ${kotlinParameters(entry.placeholders)}): String =`,
    `        context.getString(R.string.${resource}, ${entry.placeholders.map((placeholder) => placeholder.name).join(", ")})`
  ];
}

function composeEntry(entry: LocalizationEntry, objectName: string): string[] {
  const name = kotlinIdentifier(entry.key, objectName);
  const resource = resourceIdentifier(entry.key);

  if (entry.kind === "array") {
    return [
      "    @Composable",
      `    public fun ${name}(): List<String> = stringArrayResource(Res.array.${resource})`
    ];
  }

  if (entry.kind === "plural") {
    const parameters = pluralParameters(entry.placeholders, false);
    const args = pluralFormatArgs(entry.placeholders);
    return [
      "    @Composable",
      `    public fun ${name}(${parameters}): String =`,
      `        pluralStringResource(Res.plurals.${resource}, quantity${args})`
    ];
  }

  if (entry.placeholders.length === 0) {
    return [
      "    @Composable",
      `    public fun ${name}(): String = stringResource(Res.string.${resource})`
    ];
  }

  return [
    "    @Composable",
    `    public fun ${name}(${kotlinParameters(entry.placeholders)}): String =`,
    `        stringResource(Res.string.${resource}, ${entry.placeholders.map((placeholder) => placeholder.name).join(", ")})`
  ];
}

function kotlinParameters(placeholders: Placeholder[]): string {
  return placeholders.map((placeholder) => `${placeholder.name}: ${kotlinType(placeholder)}`).join(", ");
}

function pluralParameters(placeholders: Placeholder[], includeContext: boolean): string {
  if (placeholders.length === 0) return "quantity: Int";
  const [first, ...rest] = placeholders;
  const firstParameter =
    first.type === "Int" || first.type === "Long" ? "quantity: Int" : `${first.name}: ${kotlinType(first)}`;
  return [firstParameter, ...rest.map((placeholder) => `${placeholder.name}: ${kotlinType(placeholder)}`)].join(", ");
}

function pluralFormatArgs(placeholders: Placeholder[]): string {
  if (placeholders.length === 0) return "";
  const [first, ...rest] = placeholders;
  const args = [first.type === "Int" || first.type === "Long" ? "quantity" : first.name, ...rest.map((placeholder) => placeholder.name)];
  return `, ${args.join(", ")}`;
}

function kotlinType(placeholder: Placeholder): string {
  switch (placeholder.type) {
    case "Double":
      return "Double";
    case "Long":
      return "Long";
    case "Int":
      return "Int";
    case "Boolean":
      return "Boolean";
    case "String":
    case "Any":
    default:
      return "String";
  }
}
