import type { LocalizationCatalog, LocalizationEntry, Placeholder, SwiftOutputConfig } from "../types.js";
import { pascalIdentifier, splitIdentifierPath, swiftIdentifier } from "../utils/names.js";
import { escapeSwiftString } from "../utils/text.js";

export function generateSwift(catalog: LocalizationCatalog, config: SwiftOutputConfig): string {
  const access = config.accessLevel ?? "internal";
  const enumName = config.enumName ?? "L10n";
  const containerType = config.containerType ?? "enum";
  const bundle = config.bundle ?? "Bundle.main";
  const table = config.tableName ? `"${escapeSwiftString(config.tableName)}"` : "nil";
  const entries = [...catalog.entries].sort((a, b) => a.key.localeCompare(b.key));

  const lines = [
    "// Generated by l10n-codegen. Do not edit.",
    "import Foundation",
    "",
    `${access} ${containerType} ${enumName} {`,
    `    private static let bundle: Bundle = ${bundle}`,
    `    private static let tableName: String? = ${table}`,
    ""
  ];

  if (containerType === "struct") {
    lines.push("    private init() {}", "");
  }

  if (config.symbolStyle === "nested") {
    lines.push(...swiftNestedEntries(access, entries, enumName, config.nestingSeparator ?? "."));
  } else {
    for (const entry of entries) {
      lines.push(...swiftEntry(access, entry, enumName), "");
    }
  }

  lines.push(
    "    private static func tr(_ key: String, _ args: CVarArg...) -> String {",
    "        let format = bundle.localizedString(forKey: key, value: key, table: tableName)",
    "        guard !args.isEmpty else { return format.replacingOccurrences(of: \"%%\", with: \"%\") }",
    "        return String(format: format, locale: Locale.current, arguments: args)",
    "    }",
    "}"
  );

  return `${lines.join("\n")}\n`;
}

function swiftEntry(access: string, entry: LocalizationEntry, enumName: string, nameOverride?: string): string[] {
  const name = nameOverride ?? swiftIdentifier(entry.key, enumName);
  const key = escapeSwiftString(entry.key);

  if (entry.kind === "array") {
    const values = (entry.items ?? []).map((item) => `"${escapeSwiftString(item)}"`).join(", ");
    return [
      "    /// Array values are embedded from the source catalog.",
      `    ${access} static var ${name}: [String] { [${values}] }`
    ];
  }

  if (entry.kind === "plural") {
    const parameters = swiftPluralParameters(entry.placeholders);
    const argumentsList = swiftPluralArguments(entry.placeholders);
    return [
      `    ${access} static func ${name}(${parameters}) -> String {`,
      `        tr("${key}"${argumentsList})`,
      "    }"
    ];
  }

  if (entry.placeholders.length === 0) {
    return [`    ${access} static var ${name}: String { tr("${key}") }`];
  }

  return [
    `    ${access} static func ${name}(${swiftParameters(entry.placeholders)}) -> String {`,
    `        tr("${key}", ${entry.placeholders.map((placeholder) => placeholder.name).join(", ")})`,
    "    }"
  ];
}

interface SwiftTreeNode {
  name: string;
  children: Map<string, SwiftTreeNode>;
  entries: Array<{
    entry: LocalizationEntry;
    memberName: string;
  }>;
}

function swiftNestedEntries(
  access: string,
  entries: LocalizationEntry[],
  enumName: string,
  separator: string
): string[] {
  const root: SwiftTreeNode = { name: "", children: new Map(), entries: [] };

  for (const entry of entries) {
    const parts = splitIdentifierPath(entry.key, enumName, separator);
    const memberSegment = parts.pop() ?? entry.key;
    let node = root;

    for (const part of parts) {
      const typeName = pascalIdentifier(part);
      const existing = node.children.get(typeName);
      if (existing) {
        node = existing;
      } else {
        const child = { name: typeName, children: new Map(), entries: [] };
        node.children.set(typeName, child);
        node = child;
      }
    }

    node.entries.push({
      entry,
      memberName: swiftIdentifier(memberSegment)
    });
  }

  return swiftTreeLines(access, root, 1);
}

function swiftTreeLines(access: string, node: SwiftTreeNode, depth: number): string[] {
  const lines: string[] = [];
  const indent = "    ".repeat(depth);

  for (const child of [...node.children.values()].sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(`${indent}${access} enum ${child.name} {`);
    lines.push(...swiftTreeLines(access, child, depth + 1));
    lines.push(`${indent}}`, "");
  }

  for (const item of node.entries.sort((a, b) => a.memberName.localeCompare(b.memberName))) {
    lines.push(...swiftEntry(access, item.entry, "", item.memberName).map((line) => `${indent}${line.trimStart()}`), "");
  }

  return lines;
}

function swiftParameters(placeholders: Placeholder[]): string {
  return placeholders
    .map((placeholder) => `_ ${placeholder.name}: ${swiftType(placeholder)}`)
    .join(", ");
}

function swiftPluralParameters(placeholders: Placeholder[]): string {
  if (placeholders.length === 0) return "_ quantity: Int";
  const [first, ...rest] = placeholders;
  const firstParameter =
    first.type === "Int" || first.type === "Long" ? "_ quantity: Int" : `_ ${first.name}: ${swiftType(first)}`;
  return [firstParameter, ...rest.map((placeholder) => `_ ${placeholder.name}: ${swiftType(placeholder)}`)].join(", ");
}

function swiftPluralArguments(placeholders: Placeholder[]): string {
  if (placeholders.length === 0) return "";
  const [first, ...rest] = placeholders;
  const args = [first.type === "Int" || first.type === "Long" ? "quantity" : first.name, ...rest.map((placeholder) => placeholder.name)];
  return `, ${args.join(", ")}`;
}

function swiftType(placeholder: Placeholder): string {
  switch (placeholder.type) {
    case "Double":
      return "Double";
    case "Int":
    case "Long":
      return "Int";
    case "Boolean":
      return "Bool";
    case "String":
    case "Any":
    default:
      return "String";
  }
}
