import { readFile } from "node:fs/promises";
import path from "node:path";
import Handlebars from "handlebars";
import type { LocalizationCatalog, LocalizationEntry, OutputConfig, Placeholder } from "../types.js";
import { kotlinIdentifier, resourceIdentifier, swiftIdentifier } from "../utils/names.js";

interface TemplateEntry extends LocalizationEntry {
  apiName: string;
  resourceName: string;
  isString: boolean;
  isPlural: boolean;
  isArray: boolean;
  hasPlaceholders: boolean;
  swiftParameters: string;
  swiftArguments: string;
  kotlinParameters: string;
  kotlinArguments: string;
  placeholders: TemplatePlaceholder[];
}

interface TemplatePlaceholder extends Placeholder {
  swiftType: string;
  kotlinType: string;
}

export async function renderCustomTemplate(
  catalog: LocalizationCatalog,
  output: OutputConfig,
  baseDir: string
): Promise<string> {
  if (!output.template) {
    throw new Error("Custom template output requires output.template.");
  }

  const templatePath = path.resolve(baseDir, output.template);
  const source = await readFile(templatePath, "utf8");
  const handlebars = createHandlebars();
  const template = handlebars.compile(source, { noEscape: true });
  return template(templateContext(catalog, output));
}

export function templateContext(catalog: LocalizationCatalog, output: OutputConfig) {
  const namespace =
    output.type === "swift"
      ? output.enumName ?? "L10n"
      : output.objectName ?? "L10n";
  const isSwift = output.type === "swift";

  const entries = [...catalog.entries]
    .sort((a, b) => a.key.localeCompare(b.key))
    .map((entry): TemplateEntry => {
      const placeholders = entry.placeholders.map(templatePlaceholder);
      return {
        ...entry,
        placeholders,
        apiName: isSwift ? swiftIdentifier(entry.key, namespace) : kotlinIdentifier(entry.key, namespace),
        resourceName: resourceIdentifier(entry.key),
        isString: entry.kind === "string",
        isPlural: entry.kind === "plural",
        isArray: entry.kind === "array",
        hasPlaceholders: entry.placeholders.length > 0,
        swiftParameters: placeholders.map((placeholder) => `_ ${placeholder.name}: ${placeholder.swiftType}`).join(", "),
        swiftArguments: placeholders.map((placeholder) => placeholder.name).join(", "),
        kotlinParameters: placeholders.map((placeholder) => `${placeholder.name}: ${placeholder.kotlinType}`).join(", "),
        kotlinArguments: placeholders.map((placeholder) => placeholder.name).join(", ")
      };
    });

  return {
    generatedHeader: "Generated by l10n-codegen. Do not edit.",
    defaultLocale: catalog.defaultLocale,
    containerName: namespace,
    isSwift,
    isKotlinAndroid: output.type === "kotlin-android",
    isKotlinCompose: output.type === "kotlin-compose",
    output,
    entries
  };
}

function createHandlebars(): typeof Handlebars {
  const handlebars = Handlebars.create();
  handlebars.registerHelper("eq", (left: unknown, right: unknown) => left === right);
  handlebars.registerHelper("not", (value: unknown) => !value);
  handlebars.registerHelper("join", (value: unknown[], separatorOrOptions: unknown) => {
    const separator = typeof separatorOrOptions === "string" ? separatorOrOptions : ", ";
    return Array.isArray(value) ? value.join(separator) : "";
  });
  return handlebars;
}

function templatePlaceholder(placeholder: Placeholder): TemplatePlaceholder {
  return {
    ...placeholder,
    swiftType: swiftType(placeholder),
    kotlinType: kotlinType(placeholder)
  };
}

function swiftType(placeholder: Placeholder): string {
  switch (placeholder.type) {
    case "Double":
      return "Double";
    case "Int":
    case "Long":
      return "Int";
    case "Boolean":
      return "Bool";
    case "String":
    case "Any":
    default:
      return "String";
  }
}

function kotlinType(placeholder: Placeholder): string {
  switch (placeholder.type) {
    case "Double":
      return "Double";
    case "Long":
      return "Long";
    case "Int":
      return "Int";
    case "Boolean":
      return "Boolean";
    case "String":
    case "Any":
    default:
      return "String";
  }
}
