defaultLocale: en
inputs:
  - type: apple-strings
    path: apple/en.lproj/Localizable.strings
  - type: apple-xcstrings
    path: apple/Localizable.xcstrings
    sourceLanguage: en
  - type: android-xml
    path: android/res/values/strings.xml
  - type: phrase
    format: nested_json
    path: phrase/en.json

outputs:
  - type: swift
    path: generated/swift/L10n.swift
    enumName: L10n
    accessLevel: public
    bundle: Bundle.main
  - type: kotlin-android
    path: generated/kotlin/android/L10n.kt
    packageName: com.example.l10n
    rImport: com.example.app.R
  - type: kotlin-compose
    path: generated/kotlin/compose/L10n.kt
    packageName: com.example.l10n
    resImport: com.example.generated.resources.Res
